# -*- coding: utf-8 -*-
"""PruebaGlobantEj3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fmJuGVcrahGX5G8UGzSjWgucsiYsnnwi

**Ejercicio 3.**

Dada una lista de cualquier longitud de entrada, escriba una función para agrupar los elementos similares en una matriz
de salida (no importa el orden). Ejemplos:

Entrada : list = [12, 25, 1, 1, 7, 25]

Salida : [[12], [7], [25, 25], [1, 1]]

Entrada : list = [6, 7, 8, 9]

Salida : [[6], [7], [8], [9]]
"""

def agruparlista(lista: list):
  resp = []
  #Identificar los diferentes elementos de la lista
  for x in set(lista):
    #Contar las veces que el elemento aparece en la lista,
    #luego añadir una lista que consiste en el elemento
    #repetido tantas veces como el conteo indique
    resp.append([x for i in range(lista.count(x))])
  return resp

print(agruparlista([12, 25, 1, 1, 7, 25]))

print(agruparlista([6, 7, 8, 9]))
