# -*- coding: utf-8 -*-
"""PruebaGlobantEj2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YF3EeyZZa5n-3FdDR_FEx1t9AOD53x61

**Ejercicio 2.**

Escriba una función que retorne en una lista de salida, solo aquellos números de una lista de entrada que satisfagan las
siguientes condiciones:
1. El número debe ser divisible por cinco.
2. Si el número es mayor que 600, no se incluye en la salida.
3. Si el número es mayor que 1000, detenga el procesamiento y retorne el resultado.

Ejemplos:

Entrada : [24, 150, 300, 660, 295, 1050, 50]

Salida : [150, 300, 295]

Entrada : [110, 720, 307, 555, 1095, 12, 300, 1000]

Salida : [110, 555]
"""

def revisionlista(lista: list):
  resp = []
  for x in lista:
    #Detener la función si el número es mayor a 1000
    if x > 1000: return resp
    #Añadir el número solo si es menor a 600 y divisible por 5
    if (x % 5 == 0) and (x < 600): resp.append(x)
  return resp

revisionlista([24, 150, 300, 660, 295, 1050, 50])

