# -*- coding: utf-8 -*-
"""PruebaGlobantEj1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kUZ_dvYIjIU_ajoIZ2XzYW9BduCJIktB

**Ejercicio 1.**

Escriba una función que retorne la suma de una serie de X número repetido hasta el n-ésimo término. Ejemplos:

Entrada : numero=3, terminos=5
Salida : 37035 (3 + 33 + 333 + 3333 + 33333)

Entrada : numero=5, terminos=3
Salida : 615 (5 + 55 + 555)
"""

def sumaserienum(numero=3, terminos=5):
  suma = 0
  for i in range(1,terminos+1):
    termino = 0
    for j in range(i):
      termino += numero*(10**j)
    suma += termino
  return suma

sumaserienum(5, 3)

